server:
  port: 8018
spring:
  profiles:
    active: k8s
  application:
    name: product-client
ribbon:
  eureka:
    enable: true
feign:
  hystrix:
    enabled: true    #在feign中开启hystrix熔断机制
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    #下面一定要写true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 5         #续约间隔时间
      lease-expiration-duration-in-seconds: 15     #续约到期时间
